version: "3.9"

services:
#Registry
  registry:
    image: registry:2
    restart: always
    ports:
    - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_TLS_CERTIFICATE: /etc/certs/certificate.crt
      REGISTRY_HTTP_TLS_KEY: /etc/certs/private.key
    volumes:
      - myregistrydata:/data
      - ./auth:/auth
      - ./nginx/ssl:/etc/certs
    networks:
      - mynet

#Nginx Service
#  nginx:
#    image: nginx:alpine
#    container_name: nginx
#    restart: unless-stopped
#    tty: true
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/conf.d/:/etc/nginx/conf.d/
#      - ./nginx/ssl/:/etc/nginx/ssl/
#    networks:
#      - mynet

#Docker Networks
networks:
  mynet:
    driver: bridge

#Volumes
volumes:
  myregistrydata:
    driver: local
